### ISSUE TITLE
Add `MacOSDnsServerAddressStreamProvider` hints

### ISSUE THREAD

**Issue by sdeleuze** [oracle/graalvm-reachability-metadata#100]
It looks like on Mac `io.netty.resolver.dns.DnsServerAddressStreamProviders` require a hint on `MacOSDnsServerAddressStreamProvider` default constructor, and maybe other ones.

@joshlong Since I am on Linux, could you please provide the required  `*.json` files that make it work (including with the `reachableType` entries)?

**Comment by violetagg** [comment]
@sdeleuze @gradinac I have fix for this. When I'm creating a PR should I include the fix to the existing `Netty 4.1.80.Final` configuration?

**Comment by sdeleuze** [comment]
Yes please.
