### ISSUE TITLE
Add thymeleaf metadata

### ISSUE THREAD

**Issue by mhalbritter** [oracle/graalvm-reachability-metadata#21]
Add metadata for `org.thymeleaf:thymeleaf:3.1.0.M2` and `org.thymeleaf:thymeleaf-spring6:3.1.0.M2`. We have [these hints](https://github.com/spring-projects/spring-aot-smoke-tests/blob/main/aot-smoke-test-third-party-hints/src/main/java/org/springframework/aot/smoketest/thirdpartyhints/ThymeleafRuntimeHints.java) in our smoke tests to make the sample work, but I guess we missed some.

**Comment by sdeleuze** [comment]
I will work on that one.
