### ISSUE TITLE
How to reduce the amount of metadata when there are a lot of reflections in the code.

### ISSUE THREAD

**Issue by wangliang181230** [oracle/graalvm-reachability-metadata#232]
**Describe the problem**
See a class:
```java
public class ClassAlias {

    private static final Map<String, Class<?>> CLASS_ALIAS = new HashMap<>();

    static {
        addAlias("class1", Class.forName("Class1")); // in the `native-image`, throw `ClassNotFoundException`.
        addAlias("class2", Class.forName("Class2"));
        addAlias("class3", Class.forName("Class3"));
        addAlias("class4", Class4.class); // in the `native-image`, the clazz will be a null value.
        addAlias("class5", Class5.class);
        addAlias("class6", Class6.class);
        ......
        addAlias("class99", Class.forName("Class99"));
        addAlias("class100", Class100.class);
    }

    public static void addAlias(String alias, Class<?> clazz) {
        CLASS_ALIAS.add(alias, clazz);
    }

}
```

Please see a specific class: https://github.com/x-stream/xstream/blob/master/xstream/src/java/com/thoughtworks/xstream/XStream.java

Can I only add 100 metadata? Or are there other simpler configurations?

**Additional context**

**System Info (please complete the following information):**
 - OS: [e.g. `Windows`]
 - GraalVM Version [e.g. `22.0 CE`]
 - Java Version [e.g. `17`]
 - Plugin version [e.g. `native-gradle-plugin:0.9.10`]

**To Reproduce**
If possible please attach a complete reproducer here (either as [a zip file](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to public repository/branch).

**Comment by vjovanov** [comment]
We are working towards a way to do this kind of definition in the code of the project. This is expected to land in the next release of GraalVM as a preview feature. Until then, we can only do this via JSON.

**Comment by wangliang181230** [comment]
OK, I understand.
Thank you for your answer.
Look forward to the next release.

**Comment by wangliang181230** [comment]
@vjovanov @dnestoro Is there a new feature?

**Comment by vjovanov** [comment]
Yes, the example above should already work with Native Image. When `forName` gets a literal it should be converted directly into a class. If that is not the case please open a ticket.
