### ISSUE TITLE
Support testing macos/windows

### ISSUE THREAD

**Issue by jvalkeal** [oracle/graalvm-reachability-metadata#24]
Currently gh actions only use linux to run tests and it'd be beneficial to enable macos and windows getting better test coverage.

I experimented enabling tests on macos/windows are here's some notes.

- On windows there's some things to change
  - We need graal 22.2.0 due to https://github.com/oracle/graal/issues/4502.
  - Line breaks cause issues with checkstyle and spotless. Works by making git to checkout without modifying line breaks and then spotless needs to be configured to use unix style breaks.
  - Quite a bit of trouble with gradle build not exiting most likely due to https://github.com/gradle/gradle/issues/3987. As tests run underlying project tests via exec task(by running gradle command), theory is that the process causing build to hung up is a gradle daemon. I mostly got build working by making sure that all tests are using main wrapper which limits created daemons as gradle version would be same. Disabling daemon on gradle run for tests might also fix this issue on windows.

- On both macos and windows
  - postgres and mysql test will fail as those were made to work only on linux runners as you get failure to launch docker container for database.
  - Tried `@EnabledOnOs(OS.LINUX)` on those tests which doesn't work on native tests due to 
  `Error: Classes that should be initialized at run time got initialized during image building:
  org.junit.jupiter.api.condition.OS was unintentionally initialized at build time.`

**Comment by linghengqian** [comment]
- I have a PR for this issue.
