### ISSUE TITLE
Re-enable JettyClientTest

### ISSUE THREAD

**Issue by dnestoro** [oracle/graalvm-reachability-metadata#259]
Currently JettyClientTest is disabled since it uses external service (see [this](https://github.com/oracle/graalvm-reachability-metadata/blob/master/tests/src/org.eclipse.jetty/jetty-client/11.0.12/src/test/java/org_eclipse_jetty/jetty_client/JettyClientTest.java#L21)) The test should be re-enabled once it is implemented not to use external services.

**Comment by dnestoro** [comment]
@mhalbritter @bclozel please try to refactor this test if possible.

**Comment by mhalbritter** [comment]
See https://github.com/oracle/graalvm-reachability-metadata/pull/276
