### ISSUE TITLE
Add missing Jetty hints

### ISSUE THREAD

**Issue by sdeleuze** [oracle/graalvm-reachability-metadata#284]
Based on my tests, the following Jetty hint is missing with Jetty `11.0.5` provided with Spring Boot 3:
```
[
  {
    "name": "org.eclipse.jetty.server.ForwardedRequestCustomizer$Forwarded",
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true
  }
]
```
cc @mhalbritter.

**Comment by mhalbritter** [comment]
I'll take a look at this.

**Comment by mhalbritter** [comment]
I wondered why our smoke tests were green. This issue only pops up when setting `server.forward-headers-strategy=native`

**Comment by mhalbritter** [comment]
Fixed in https://github.com/oracle/graalvm-reachability-metadata/pull/285

**Comment by sdeleuze** [comment]
Thanks!
