### ISSUE TITLE
BUG: index.json file format error

### ISSUE THREAD

**Issue by yuluo-yx** [oracle/graalvm-reachability-metadata#326]
**Describe the bug**
This problem occurs when I add metadata for nacos-client. I use first
`./gradlew scaffold --coordinates com.alibaba:nacos-client:2.2.1` command to generate relevant templates, and then fill in metadata file content.When I submitted the pr, I found that there were rows deleted. Observe the file and find that the index.json file has been modified. Not in accordance with the previous file format.

```json
[ {
  "allowed-packages" : [ "org.example" ],
  "directory" : "org.example/library",
  "module" : "org.example:library"
}, {
  "allowed-packages" : [ "org.jline", "org.fusesource" ],
  "directory" : "org.jline/jline",
  "module" : "org.jline:jline"
}, {
  "allowed-packages" : [ "org.jline", "org.fusesource" ],
  "module" : "org.jline:jline-terminal",
  "requires" : [ "org.jline:jline" ]
}, {
  "allowed-packages" : [ "org.jline", "org.fusesource" ],
  "module" : "org.jline:jline-console",
  "requires" : [ "org.jline:jline" ]
}, {
  "allowed-packages" : [ "org.jooq" ],
  "directory" : "org.jooq/jooq",
  "module" : "org.jooq:jooq"
}, {
  "allowed-packages" : [ "org.h2" ],
  "directory" : "com.h2database/h2",
  "module" : 
...
```

The following is the result of automatic formatting using ctrl alt l in my idea, which is still different from the previous index and json files. I'm sure I didn't make any formatting changes to the index.json file other than adding some metadata files and unit test related stuff

```json
{
    "directory": "org.example/library",
    "module": "org.example:library",
    "allowed-packages": [
      "org.example"
    ]
    ],
    "directory": "org.example/library",
    "module": "org.example:library"
  },
```

**Comment by dnestoro** [comment]
This was probably result of some update in checkstyle task, but even with that, our style checks are passing, so this is probably not something that will break anything.
