### ISSUE TITLE
Metadata for Logback 4.1.1

### ISSUE THREAD

**Issue by sdelamo** [oracle/graalvm-reachability-metadata#396]
To upgrade [logback to 1.4.11 in the Micronaut Framework](https://github.com/micronaut-projects/micronaut-core/pull/9857), we had to add the following [GraalVM Configuration Metadata](https://www.graalvm.org/latest/reference-manual/native-image/dynamic-features/Reflection/#manual-configuration) via `reflect-config.json` file: 

```json
[
  {
    "name": "ch.qos.logback.classic.joran.SerializedModelConfigurator",
    "methods": [
      {
        "name": "<init>",
        "parameterTypes": [

        ]
      }
    ]
  },
  {
    "name": "ch.qos.logback.classic.util.DefaultJoranConfigurator",
    "methods": [
      {
        "name": "<init>",
        "parameterTypes": [

        ]
      }
    ]
  }
]
```

[I created an issue in the logback repository ](https://github.com/qos-ch/logback/issues/703). However, I have seen there is already metadata for 'ch.qos.logback:logback-classic' in this repository. Thus, it maybe worth it add it here.

**Comment by msupic** [comment]
Those have been already added as part of this PR: https://github.com/oracle/graalvm-reachability-metadata/pull/391 and will be visible in the next metadata release.

**Comment by sdelamo** [comment]
@msupic can you create an issue in Micronaut core and add it to the GitHub Project so that we don't forget to remove it from the Micronaut repository.
