### ISSUE TITLE
Logback 1.4.9 reflect-config.json missing ContextInitializer

### ISSUE THREAD

**Issue by martijndwars** [oracle/graalvm-reachability-metadata#454]
**Describe the bug**
When using the [reflect-config.json](https://github.com/oracle/graalvm-reachability-metadata/blob/5c86681610fb0ead8acc1d370170f1220ccbf637/metadata/ch.qos.logback/logback-classic/1.4.9/reflect-config.json) for Logback 1.4.9, no logs are seen on the console.

**To Reproduce**
See attached [logback-native.zip](https://github.com/oracle/graalvm-reachability-metadata/files/14327984/logback-native.zip).
```
mvn clean install
native-image -jar target/logback-native-0.1-SNAPSHOT.jar
./logback-native-0.1-SNAPSHOT
```

**Expected behavior**
See log output on the console.

**Additional context**
[reflect-config.json](https://github.com/oracle/graalvm-reachability-metadata/blob/5c86681610fb0ead8acc1d370170f1220ccbf637/metadata/ch.qos.logback/logback-classic/1.4.9/reflect-config.json) loads the following two classes if `ch.qos.logback.classic.util.ContextInitializer` is reachable:

* `ch.qos.logback.classic.util.DefaultJoranConfigurator`
* `ch.qos.logback.classic.joran.SerializedModelConfigurator`

However, according to the [ContextInitializer.java](https://github.com/qos-ch/logback/blob/v_1.4.9/logback-classic/src/main/java/ch/qos/logback/classic/util/ContextInitializer.java) sources `ch.qos.logback.classic.BasicConfigurator` is also loaded reflectively, but this class is missing from the reflect-config. As such, the BasicConfigurator is never run, and some essential configuration is missing.

**Comment by wilkinsona** [comment]
https://github.com/oracle/graalvm-reachability-metadata/pull/458 should fix this.

**Comment by martijndwars** [comment]
Thank you @wilkinsona!
