### ISSUE TITLE
[QUESTION] How to add comments?

### ISSUE THREAD

**Issue by xuxiaocheng0201** [oracle/graalvm-reachability-metadata#514]
**Describe the problem**
How to add comments in the metadata json file?

**Additional context**
Is the metadata json file based on the JSON5 scheme?
Or add a '_comment' field?

**Comment by linghengqian** [comment]
- You just need to use GraalVM CE Dev For JDK23 or GraalVM CE Dev For JDK24 which have not been released yet. The relevant PR is at https://github.com/oracle/graal/pull/9048 .
