### ISSUE TITLE
Several empty blocks in the Hibernate ORM metadata

### ISSUE THREAD

**Issue by Sanne** [oracle/graalvm-reachability-metadata#55]
I was having a quick look into the Hibernate ORM metadata, and found some strange things such as valid blocks with valid conditionals, but pointing to empty lists of type to be made reachable.

```
   {
    "condition": {
      "typeReachable": "org.hibernate.bytecode.internal.bytebuddy.ByteBuddyState$ProxyDefinitionHelpers$1"
    },
    "interfaces": []
  },
```

I suppose these are harmless, but tracking here as something that should be looked at.

https://github.com/oracle/graalvm-reachability-metadata/blob/bb36403180544e182008266edc9340f37c1a4fcb/metadata/org.hibernate.orm/hibernate-core/6.1.1.Final/proxy-config.json#L512

**Comment by sdeleuze** [comment]
@gradinac Something to refine on the agent side maybe?

**Comment by Sanne** [comment]
Thanks for the quick fix! Just curious, did you amend these manually or was the tooling improved?

**Comment by Sanne** [comment]
Thanks, that's good to know.

I hope we'll (eventually?) be able to refine the agent to have enough configuration capabilities (or automation such as to avoid emitting empty blocks), as I'd prefer to have this generated by the ORM build on each CI run, and have any discrepancies flagged.
Not sure yet how we'll act on such "flagging" but it would be good to know if a code change has consequences on the metadata needs - intended or not.

Perhaps someone on my team can contribute to the agent.

**Comment by sdeleuze** [comment]
@gradinac Should we create a related https://github.com/oracle/graal issue?
