### ISSUE TITLE
please add support for the Reactive PostgreSQL R2DBC driver

### ISSUE THREAD

**Issue by joshlong** [oracle/graalvm-reachability-metadata#79]
right now there's some metadata required to make it work that isn't there yet. for example, reflective hints around `Instant[].class` and `ZonedDateTime[].class`

**Comment by nkonev** [comment]
Seems it is already added here https://github.com/pgjdbc/r2dbc-postgresql/blob/main/src/main/resources/META-INF/native-image/org.postgresql/r2dbc-postgresql/reflect-config.json#L123

**Comment by linghengqian** [comment]
- @msupic Please help close this issue.

**Comment by msupic** [comment]
As @nkonev already wrote above, metadata for PostgreSQL R2DBC driver can be found in the driver itself since `1.0.0.RELEASE` version. If something is missing in their metadata, please create an issue in their github page.
