### ISSUE TITLE
Tests contain wrong default tckPath

### ISSUE THREAD

**Issue by jvalkeal** [oracle/graalvm-reachability-metadata#8]
**Describe the bug**
All `settings.gradle` files in tests uses wrong relative path(one directory off) to `tck-build-logic`.

**To Reproduce**
```bash
~/repos/jvalkeal/graalvm-reachability-metadata/tests/src/org.example/library/0.0.1

$ ../../../../../gradlew projects
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.4.1/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 

FAILURE: Build failed with an exception.

* Where:
Settings file '/home/jvalkealahti/repos/jvalkeal/graalvm-reachability-metadata/tests/src/org.example/library/0.0.1/settings.gradle' line: 17

* What went wrong:
Error resolving plugin [id: 'org.graalvm.internal.tck-settings', version: '1.0.0-SNAPSHOT']
> Included build '/home/jvalkealahti/repos/jvalkeal/graalvm-reachability-metadata/tck-build-logic' does not exist.

```
**Expected behavior**
Should be able to run project without setting `GVM_TCK_TCKDIR`.

**System Info (please complete the following information):**
 - OS: `Ubuntu`
 - GraalVM Version `22.1 CE`
 - Java Version `17`

**Comment by lazar-mitrovic** [comment]
This should be fixed by [this commit](https://github.com/oracle/graalvm-reachability-metadata/commit/7b573d3d21f1f7e61a9148a524fbb43d5a507bf4#diff-84be6e3e35445405d7233ec291da9a51bdf4fc80517c8887e7031896b5989147).
