### ISSUE TITLE
MySql connector 8.0.31 broken with Maven due to relocation

### ISSUE THREAD

**Issue by sdeleuze** [oracle/graalvm-reachability-metadata#86]
With MySql connector `8.0.31`, when using Maven we see a message `The artifact mysql:mysql-connector-java:jar:8.0.31 has been relocated to com.mysql:mysql-connector-j:jar:8.0.31` and the related metadata are not registered likely because `mysql:mysql-connector-java` does not match with `com.mysql:mysql-connector-j`. We should probably introduce metadata for `com.mysql:mysql-connector-j:jar:8.0.31` and check in the test there is no regression.

**Comment by mhalbritter** [comment]
Going to fix this.
